name: live_charts
description: A library for creating live charts.
version: 0.0.2
author: rinukkusu <rinukkusu@auen.land>
homepage: https://github.com/rinukkusu/live_charts

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
